name: Robert Krijthe
favicon: null
layout_spectrum: 0.90902
typography_spectrum: 0.7978262177202851
title: Ultimate Coaching
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#d5a89d'
    - '#211811'
    - '#666027'
    - '#9a3046'
  brandStrength: 0.75
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
