name: Robert Krijthe
favicon: null
layout_spectrum: 0.90902
typography_spectrum: 0.7978262177202851
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7a706e'
    - '#0d0d0d'
    - '#454146'
    - '#e3e3e3'
    - '#b6aeb5'
  brandStrength: 0
  lightness: 0.125
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
